syncsets = {
    # TODO: Add / Edit / Delete from this list as needed, try out!!!
    '__Program'                  :['tc_EOF'],
    '__ProgramDefinition'        :['tc_SEMICOL'],
    '__IdentifierList'           :['tc_RPAREN','tc_COLON','tc_SEMICOL'],
    '__IdentifierListRest'       :[],
    '__Declarations'             :['tc_FUNCTION','tc_PROCEDURE','tc_BEGIN'],
    '__DeclarationsRest'         :[],
    '__Type'                     :['tc_SEMICOL','tc_VAR','tc_FUNCTION','tc_PROCEDURE'],
    '__StandardType'             :['tc_SEMICOL','tc_VAR','tc_FUNCTION','tc_PROCEDURE'],
    '__SubprogramDeclarations'   :['tc_BEGIN','tc_SEMICOL'],
    '__SubProgramHead'           :['tc_SEMICOL','tc_VAR','tc_BEGIN'],
    '__Arguments'                :['tc_COLON','tc_SEMICOL'],
    '__ParameterList'            :['tc_RPAREN','tc_COLON','tc_SEMICOL'],
    '__CompoundStatement'        :['tc_DOT','tc_SEMICOL','tc_END','tc_BEGIN'],
    '__StatementList'            :['tc_END'],
    '__Statement'                :[],
    '__Variable'                 :['tc_ASSIGNOP','tc_ADDOP','tc_MULOP','tc_ID','tc_NUM','tc_LPAREN','tc_RPAREN','tc_NOT'],
    '__ProcedureStatement'       :['tc_SEMICOL','tc_END'],
    '__ExpressionList'           :['tc_RPAREN'],
    '__SimpleExpression'         :['tc_RELOP'],
    '__Term'                     :['tc_ADDOP'],
    '__Factor'                   :[]
}

syncsets2 = {
    # These sync sets just include the follow tokens and are specific
    # for Hrafn's grammar, given with 'Project 2 - comments'.
    '__Program'                  :['tc_EOF'],
    '__ProgramDefinition'        :['tc_SEMICOL'],
    '__IdentifierList'           :['tc_RPAREN','tc_COLON'],
    '__IdentifierListRest'       :[],
    '__Declarations'             :['tc_FUNCTION','tc_PROCEDURE','tc_BEGIN'],
    '__Type'                     :['tc_SEMICOL'],
    '__StandardType'             :[],
    '__SubprogramDeclarations'   :['tc_BEGIN'],
    '__SubprogramDeclaration'    :['tc_SEMICOL'],
    '__SubProgramHead'           :['tc_BEGIN'],
    '__Arguments'                :['tc_SEMICOL'],
    '__ParameterList'            :['tc_RPAREN'],
    '__ParameterListRest'        :[],
    '__CompoundStatement'        :['tc_DOT','tc_SEMICOL'],
    '__OptionalStatements'       :['tc_END'],
    '__StatementList'            :['tc_END'],
    '__StatementListRest'        :[],
    '__Statement'                :['tc_END','tc_SEMICOL'],
    '__ArrayReference'           :[],
    '__IdOrProcedureStatement'   :['tc_END','tc_SEMICOL'],
    '__ExpressionList'           :['tc_RPAREN'],
    '__ExpressionListRest'       :[],
    '__Expression'               :['tc_COMMA','tc_RPAREN'],
    '__SimpleExpressionRelop'    :[],
    '__SimpleExpression'         :['tc_RELOP','tc_RPAREN'],
    '__Term'                     :['tc_ADDOP'],
    '__Factor'                   :[]
}